on:
  push:
    branches:
      - 'v/**'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'Release: ${{ github.ref_name }}',
              owner,
              repo,
              head: '${{ github.ref_name }}',
              base: 'master',
            });
